name = "Promethium Optimized"
author = "yangdawn"
version = "2.0.0-alpha.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "812dd80513771189befe092b0f06bd73fe8dd7b71dce4b5bf1707ebba8c745dc"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
